name: test:integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run integration test
        run: yarn run test:integration
